name: cineva_ui
description: Cineva design system — primitives, chrome et composants de contenu.
publish_to: none
version: 0.1.0

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cineva_models:
    path: ../models
  cineva_theme:
    path: ../theme

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
